### ISSUE TITLE
Cannot run sample on MacOS

### ISSUE THREAD

**Issue by mattraffel** [streetcred-id/agent-framework#108]
**Describe the bug**
Sample WebAgent crashes on run. 

> matt@macbob:~/src/work/agent-framework$ dotnet run --project samples/aspnetcore/WebAgent.csproj
> info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
>       User profile is available. Using '/Users/matt/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
> Application startup exception: System.DllNotFoundException: Unable to load shared library 'indy' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libindy, 1): image not found

I created a link to indy, so the error doesn't make much sense.

> matt@macbob:~/src/work/agent-framework$ ls -l samples/aspnetcore/bin/Debug/netcoreapp2.0/
> total 752
> -rw-r--r--  1 matt  staff  297018 Feb 15 10:27 WebAgent.deps.json
> -rw-r--r--  1 matt  staff   33792 Feb 15 10:27 WebAgent.dll
> -rw-r--r--  1 matt  staff    5692 Feb 15 10:27 WebAgent.pdb
> -rw-r--r--  1 matt  staff     208 Feb 15 10:27 WebAgent.runtimeconfig.dev.json
> -rw-r--r--  1 matt  staff     210 Feb 15 10:27 WebAgent.runtimeconfig.json
> lrwxr-xr-x  1 matt  staff      64 Feb 15 10:28 indy -> /Users/matt/src/work/indy-sdk/libindy/target/debug/libindy.dylib
> -rw-r--r--  1 matt  staff    3068 Feb 15 08:49 pool_genesis.txn

**To Reproduce**
1. run command `dotnet run --project samples/aspnetcore/WebAgent.csproj`

**Expected behavior**
Service started and able to navigate to page in browser

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS, Mojave 10.14.3

**Comment by tplooker** [comment]
@mattraffel thanks for your report, @tmarkovski are you able to look at this?

**Comment by tmarkovski** [comment]
@mattraffel Can you try copying `libindy.dylib` to `/usr/local/lib`? `DllImport` search path works differently when you use it with `dotnet run` since the running context is your current directory.

**Comment by mattraffel** [comment]
Creating a link to libindy.dylib in `/usr/local/lib` did allow the program to run.  

For my own curiosity -> this solution doesn't make sense given following context:  for another dotnet core project (on the same mac) if I copy (or create the symbolic link) to `libindy.dylib` in the `bin/Debug/netcoreapp2.0` folder, the app runs ok.  I did not need indy in `/usr/local/lib`.  The difference is that app is a console app not a web service.  does that have something to do with it?

**Comment by tmarkovski** [comment]
I'm not entirely sure. It seems the search path is somewhat inconsistent. Here's what the documentation says about it.

https://www.mono-project.com/docs/advanced/pinvoke/#macos-framework-and-dylib-search-path

**Comment by mattraffel** [comment]
much appreciated :)
