### ISSUE TITLE
Allow an environment variable to establish the name associated with the agent instance

### ISSUE THREAD

**Issue by swcurran** [streetcred-id/agent-framework#113]
**Is your feature request related to a problem? Please describe.**
Using this agent for a demo and this would make it easier to demo

**Describe the solution you'd like**
Allow the user to have an Environment Variable set that is the name of to be used for the Agent Instance rather than generating the name.  We want to use this agent as is in a Web Demo and it would help us tell the story if we can have the user enter their name.

**Describe alternatives you've considered**
Leave it as is :-)

**Additional context**
We're using the agent in a workshop in a way such that the customizable agent instance names would make things easier for those participating in the workshop.

The workshop is on Monday, March 13, so if this can't be done by then, don't worry about it.  Although the workshop is pretty neat, so we might get a chance to use it again.

**Comment by tmarkovski** [comment]
@tplooker submitted a PR to fix this. You can now use environment variable `AGENT_NAME` to specify the name of agent. This will propagate into connection negotiation. For completeness, I'll mention that you can configure env var `ENDPOINT_HOST` as the Url the agent will use in communicating their agent endpoint. This url doesn't affect any server configuration bindings.
@swcurran
