### ISSUE TITLE
Support the sending of an Invitation via a Basic Message 

### ISSUE THREAD

**Issue by swcurran** [streetcred-id/agent-framework#116]
**Is your feature request related to a problem? Please describe.**
Sort of...the problem is that sending a basic message doesn't seem to work for long messages.

**Describe the solution you'd like**
To support the demo we are planning at the Vancouver Indy Bootcamp, we'd like to be able to send an invitation via the Basic Message protocol.  We'll send you the details of the bootcamp we're preparing (as soon as it is ready).  In one of the steps, a user on an instance of the StreetCred agent generates an invitation and sends it to a connected agent via the Basic Message interface.  On the StreetCred agent, the message is not sent and is a bit of a mess on the screen.

Please try this scenario and ensure the message gets sent and the screen looks OK.

**Describe alternatives you've considered**

**Additional context**
Here is an example of what is displayed when sending an invitation as a basic message.  The message was not actually sent, but does display (badly) on the screen.

![image](https://user-images.githubusercontent.com/1018050/53997849-a66dfc80-40f2-11e9-9e3a-5b615942bf57.png)

**Comment by tplooker** [comment]
@tmarkovski have we resolved this one?

**Comment by tmarkovski** [comment]
Yup. Can be closed.
