### ISSUE TITLE
Add sent_time arg to basic message and use local time in browser

### ISSUE THREAD

**Issue by swcurran** [streetcred-id/agent-framework#117]
**Is your feature request related to a problem? Please describe.**
Found a couple of time related issues in the agent - one in the protocol and one in the UI.  In the protocol, the Street Cred agent is not including the "sent_time" parameter in the message.  It would be nice if it did.  Some agents are displaying that in their UI.  As well, where time is displayed (such as the main screen - connections list), please use the local time in the browser vs. the UTC time.  Or at least add an indicator to say it is UTC time.

**Describe the solution you'd like**
Add the sent_time parameter to the send BasicMessage message type.
When displaying time in the browser, convert to local time for the browser.

Probably those should be two issues, but...  :-)

**Describe alternatives you've considered**
Ignore it.  Which is fine as well :-).

**Additional context**
Here is what a message sent from Street Cred looks like in the Indy Agent UI.

![image](https://user-images.githubusercontent.com/1018050/54046050-1d090980-4188-11e9-8ed9-91284f2d1b1e.png)

**Comment by tmarkovski** [comment]
Thanks for reporting these @swcurran .
I added this based on the basic message hipe using ISO 8601 UTC formatted string date.
UI updated.

![image](https://user-images.githubusercontent.com/1280118/54050008-24daa500-41ac-11e9-90af-cc9906edc075.png)

**Comment by swcurran** [comment]
Nice!!! Thanks.
