### ISSUE TITLE
Sample app crashes on nokia 6.1

### ISSUE THREAD

**Issue by burdettadam** [streetcred-id/agent-framework#131]
**Describe the bug**
When I deploy AFMobileSample Android app to my Nokia 6.1 and run it, clicking the provision button causes the app to crash. 
I am using VS on windows 10 and my phone is up to date. 
Logs show that the sample app is not able to load indy. https://gist.github.com/burdettadam/2f097f98d29202af1280b316be6de3ad#file-nokia_6-1_afs_logcat-L12

**To Reproduce**
1. In Visual Studio(VS) on Windows 10, build and deploy android sample app to Nokia 6.1 phone.
2. launch the sample app on the phone.
3. open logcat in VS. 
3. click provision button.
4. See the error in logcat.

**Expected behavior**
indy dependancies being loaded and app not crashing. 

**Screenshots**
https://gist.github.com/burdettadam/2f097f98d29202af1280b316be6de3ad#file-nokia_6-1_afs_logcat-L12

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: nokia 6.1
 - OS: Android
 - Version: Android Version 9

**Comment by tplooker** [comment]
@burdettadam Can you confirm the same issue occurs on other android devices i.e an emulator?

**Comment by tmarkovski** [comment]
@tplooker He can run in the emulator, though had to manually copy x86 libs, we forgot to include them in the sample. Issue only occurs on the device.

@burdettadam If you can wrap the calls to provision the agent in try/catch and post the managed .NET exception (with stack trace), that would be very helpful.

**Comment by tmarkovski** [comment]
@burdettadam @tplooker  I assume you guys got past this problem. Please re-open if needed.
