### ISSUE TITLE
InvalidStateException when creating a schema

### ISSUE THREAD

**Issue by idr-spilling** [streetcred-id/agent-framework#160]
**Describe the bug**
Receiving the following exception when attempting to create a schema using a new wallet.
`Hyperledger.Indy.InvalidStateException: The SDK library experienced an unexpected internal error.at AgentFramework.Core.Runtime.DefaultPoolService.GetPoolAsync(String poolName) in C:\Projects\passport\agent-framework\src\AgentFramework.Core\Runtime\DefaultPoolService.cs:line 32`

**To Reproduce**
1. Deployed app to Azure
2. Configured WalletOptions and PoolOptions:
```
"WalletOptions": {
    "WalletConfiguration": {
      "Id": "issuer_wallet_1",
      "StorageConfiguration": { "Path": "D:\\home\\site\\indy\\" }
    },
    "WalletCredentials": { "Key": "issuer_wallet_key_1" }
  },
  "PoolOptions": {
    "GenesisFilename": "genesis.txn",
    "PoolName": "default_pool1",
    "ProtocolVersion": 2
  }
```
(The genesis.txn file is in place)
3. Configured using endpoint of https://<domain>/agent 
4. Configured 
```
app.UseAgentFramework<PassportAgentMiddleware>(agentEndpoint,
  obj =>
  {
     obj.AddIssuer("000000000000000000000000Trustee1");
     obj.AddOwnershipInfo(agentName, logoUrl);
   });
```
5. Opened app with a browser and use the method ISchemaService.CreateSchemaAsync.
6. It fails with the error above.

**Expected behavior**
The method should return the schema id.

**Azure:**
 - OS: App Service, Windows, Central US

Using Hyperledger.Indy.Sdk 1.8.0 from NuGet.
Using AgentFramework built from https://github.com/idramp/agent-framework/tree/idr/develop

**Comment by tplooker** [comment]
@idr-spilling do you have the indy-cli installed, can you please try create a pool configuration using the cli with the txn file you have mentioned above and confirm connection to the node pool?

**Comment by idr-spilling** [comment]
I ran the indy-cli using the following commands on both my local machine and in Azure.
For both I receive the following output:
```
pool delete default_pool1
Pool "default_pool1" has been deleted.

pool create default_pool1 gen_txn_file=genesis.txn
Pool config "default_pool1" has been created

pool connect default_pool1
Error: Invalid library state
  Caused by: Ledger merkle tree is not acceptable for current tree.
```
I am now investigating our private nodes and the txn file.

**Comment by idr-spilling** [comment]
We are running a set of private nodes for testing. The nodes themselves report that they are running. The ports on the VM are open and responding. 

We are using the `pool_transactions_genesis` file from the server to establish a connection. The default 127.0.01 IP address in the file has been replaced by the VM's public IP address. 

The result of the `pool connect` command remains the same as above. This is the result using indy-cli versions 1.8.0 and above.

**Comment by tmarkovski** [comment]
@idr-spilling Do you run the nodes by passing the public IP as well? If you run them using 127.0.0.1 that IP will be registered on the nodes. If you're using the docker file from indy-sdk/ci you can pass an argument to docker with the public IP they should bound to `pool_ip`.

**Comment by NateHayes** [comment]
No, we are only running it with the local host IP address. Then we take the genesis file, and find-replace `127.0.0.1` with the public IP address

**Comment by tmarkovski** [comment]
```
docker build --build-arg pool_ip=PUBLIC_IP -f ci/indy-pool.dockerfile -t indy_pool .
docker run -itd -p 9701-9709:9701-9709 indy_pool
```

Or just replace the `pool_ip` inside the docker file.

**Comment by idr-spilling** [comment]
It appears this was the issue. When the nodes were originally configured, the public address was not used. 
Thank you for your assistance.
