### ISSUE TITLE
SDK name change

### ISSUE THREAD

**Issue by tmarkovski** [streetcred-id/agent-framework#55]
With the SDK being published under open source license, I'd like to propose a change in the name of it to reflect the nature of the library.

Things that will change:

- Repository name
- Library name (Project, Solution, Assembly)
- Namespaces
- Packages

Things that won't change:

- Location and organization repo
- License copyright notice

Please share any thoughts you have on this matter.

Furthermore, I suggest we change the Extensions package to be suffixed with `AspNetCore` instead, which is a standard practice for packages intended for the web project targets.

**Comment by tmarkovski** [comment]
@tplooker @dznz @DeniSpasovski @PawelJargielo @joshhill - Please let me know if this is something your current efforts can withstand without a lot of things breaking. I understand this is a breaking change, but I'd rather do this sooner rather than later.

**Comment by tplooker** [comment]
@tmarkovski I agree that is a good idea, we are happy to cater for that breaking change. What names did you have in mind?

**Comment by tmarkovski** [comment]
I don't know, I would go back to the original agent framework name. Some thoughts I had:

- Indy Agent Framework
- Repo: indy-agent-framework
- Namespace: Indy.AgentFramework (Indy.AgentFramework.AspNetCore for extensions)
- Package, Assembly - same as above

**Comment by jljordan42** [comment]
@swcurran would be nice to coordinate with this idea for von_anchor ... which is similar to this but python approach

**Comment by dznz** [comment]
Definitely keen on an "Indy" based name - is it possible to get the project under Indy itself? Otherwise they may not be wild about a project that isn't "endorsed" by them?

**Comment by tplooker** [comment]
Shall we consult the indy team? The other option I thought might be plausible is indy-agent-sdk? Could be good to push for the establishment of an agents folder in indy with a sub-folder for SDK's, perhaps VCX could be shifted to here?

**Comment by swcurran** [comment]
I think "Indy Agent" is way too general. There is already a repo called that in hyperledger, so if there is hope for moving it to HL, that will be a problem.  Everything is an Indy Agent.

I think the .NET root of the library should be included, with the assumption that this will evolve into THE basis for building any .NET agent.   I think there will be a need to put this in Indy along with other Indy Wrappers that go WAY beyond what the libindy wrappers do.

I think the name should also reflect that this is the basis for building agents, not an agent itself.  That was the evolution of the "VON Anchor" name - it was originally called "VON Agent", but that was confusing, since by itself, it is not an Agent.  The use of the term "Anchor" might be synergistic with what we are doing.  Other terms that suggest "core" might be good.  Like "core" :-).

**Comment by tplooker** [comment]
On further thought I quite like indy-agent-framework, perhaps we should seek advise from HL?

@swcurran unfortunately in the .Net world, the usage of "core" would confuse c# developers as the newest release .Net is ".Net core". I think Anchor might clash with the nomenclature of "Trust Anchor" with sovrin?

**Comment by tmarkovski** [comment]
The original project that spawned this work is https://github.com/streetcred-id/agent-framework
In the dotnet ecosystem, there are notable libraries named in this fashion - Entity Framework, Bot Framework, even .NET Framework, so Agent Framework fits nicely in my opinion. Prefixing it with Indy is OK, since it's currently only supporting indy node and indy sdk integration.

There aren't any plans at this time to move this project under Hyperledger. High level libraries like this SDK, Von Anhor, even VCX are contributions that add value to Indy while being separate from the main project. Discoverability comes naturally - we can start publishing packages to nuget.org now, and keep myget.org for nightly builds.

**Comment by tmarkovski** [comment]
SDK name has changed to Agent Framework. The was the name of the initial framework for creating application level library for the .NET Core stack, that now lives at https://github.com/streetcred-id/agent-framework-legacy

PR #60 for details on namespace and package changes.
