### ISSUE TITLE
WalletService.GetWalletAsync() invalid wallet handles being cached.

### ISSUE THREAD

**Issue by tplooker** [streetcred-id/agent-framework#61]
**Describe the bug**

Wallet service returns invalid wallets due to bad cache.

**To Reproduce**

1. Call WalletService.GetWalletAsync() with valid wallet configuration and credentials.
2. On the returned wallet object call .DisposeAsync().
3. Call WalletService.GetWalletAsync() with the same wallet configuration and credentials in step one.
4. Try use the new wallet handle in any operation.
5. Wallet in invalid state exception is thrown

**Expected behavior**

Repeated fetches the WalletService.GetWalletAsync() should not returned bad cached wallet handles that have been disposed.

**Comment by tmarkovski** [comment]
Interesting problem. `Wallet.Dispose()` only calls libindy and frees the handle with it, but not with the `WalletService` as it doesn't know about it. Two possible solutions:
- Wrap the `Wallet` class and override `Dispose` to allow the framework to properly dispose it
- Use reflection to check if private field `Wallet._requiresClose` is `false`. If so, treat as disposed and acquire a new one when calling `WalletService.GetWalletAsync`

**Comment by tplooker** [comment]
I've submitted a [PR](https://github.com/hyperledger/indy-sdk/pull/1324) to indy-sdk that exposes a new field on the wallet object that will allow for us to detect if the underlying wallet handle is still valid.

**Comment by tmarkovski** [comment]
The Indy SDK package at https://www.myget.org/feed/Packages/agent-framework contains the fix with the PR you submitted. Is there anything you wanted to the add for this issue in the framework code?

**Comment by tplooker** [comment]
@tmarkovski yeap I wanted to modify, the wallet service so that you cannot obtain an invalid wallet handle. Has this Agent-Framework repo been re-targeted to our indy sdk wrapper package?
