### ISSUE TITLE
API null checks

### ISSUE THREAD

**Issue by tmarkovski** [streetcred-id/agent-framework#7]
Possible implementation using Fody.NullGuard
- [ ] Add default Weaver file to SDK project, may need to be added manually. 
- [ ] Validate that Fody nuget is added only as development dependency and not included in the created SDK package
- [ ] API should be updated to decorate input and output values that allow nulls.
- [ ] A unit test showing expected exception

**Comment by tplooker** [comment]
@tmarkovski do we still want to use this approach? If so I can begin the implementation.

**Comment by tmarkovski** [comment]
I vote 👎 on this. It's a nice tool, but it creates this side-effect of a feature that's not immediately visible from the code. And with C# 8.0 introducing non-nullable types by default, I think we can pass on this.

**Comment by tplooker** [comment]
Agreed, I will close.
