### ISSUE TITLE
CreatedAt and ModifiedAt for wallet records

### ISSUE THREAD

**Issue by tplooker** [streetcred-id/agent-framework#74]
**Is your feature request related to a problem? Please describe.**

It is useful for providing context around when a wallet record was created or last modified at. The explicit use cases I am targeting is providing support to show when an invite/offer/request was received.

**Describe the solution you'd like**

Implement support for the fields on `RecordBase`, support updating the fields automatically in the `WalletRecordService`

**Comment by tmarkovski** [comment]
Perhaps add them as searchable get only properties, so they can be queried with "updated > last week"
