### ISSUE TITLE
Support for multi-party connection invitations

### ISSUE THREAD

**Issue by tplooker** [streetcred-id/agent-framework#92]
**Is your feature request related to a problem? Please describe.**

For some parties such as organizations or businesses it would be beneficial to be able to generate an indefinite invitation suitable for multiple parties to use to connect.

Currently invitation generation is done on an individual basis.

**Describe the solution you'd like**

- The ability to generate an invitation that multiple parties can respond to with a connection request.
- Potentially the ability to revoke an invitations validity.

**Comment by tplooker** [comment]
Im unsure whether we want to tie this to the provisioning setup it, your first suggestion feels closer to what I was thinking. I do believe multiple public invites may be common, or another way to think about them is just multi-party invites rather than public. For example I might generate a multi-party invite and put it on my website, for public consumption. I might also generate another multi-party invite for a conference i am presenting at and at the end I might include a QR code for people to connect with me? For a business it may be useful to be able to have different invites for different mediums to understand how new customers / existing customers are reaching out and connecting.

**Comment by tplooker** [comment]
Being able to individually revoke these invites I believe could be useful too, hence why I think handling the in the connection service is more appropriate.

**Comment by tmarkovski** [comment]
Good point. Extending the ConnectionRecord with a searchable flag sounds like a good idea. We could add another list method `ListPublicInvitations` to only filter these types and update the other lists accordingly to exclude them. ProcessRequest should also be updated to make sure it creates a new ConnectionRecord instead searching for existing one. RevokeInvitation method added to ConnectionService which would delete the ConnectionRecord for public invitation (or private), and delete the associated key.
Anything else I'm missing? Any other features we should include? Anything around Url generation, or leave it up to implementers.
