### ISSUE TITLE
Service Events

### ISSUE THREAD

**Issue by tplooker** [streetcred-id/agent-framework#95]
**Is your feature request related to a problem? Please describe.**

In order to support use cases such as header-less workflow. We need our baseline services to expose a base set of events for actions that are occurring.

**Describe the solution you'd like**
Add basic events to Credential, Proof and Connection Services raising events such as OnConnectionRequestReceived, OnProofRequestReceived.

**Comment by tplooker** [comment]
Thoughts on this so far would be instead of using events, inject a new service called IEventService that implements a pub-sub type approach, where other upsteam or tangential components could subscribe.

For each message processing method in the service we would raise two events using the event service, before and after message processing.

**Comment by tmarkovski** [comment]
What about using reactive extensions instead? https://github.com/dotnet/reactive
I'm not a big fan of conventional events, they're often a reason for memory leaks, though mostly on the consumer side. I've used reactive extensions before, they work great.

**Comment by tplooker** [comment]
Implementation complete, elected to raise only a single event after successful processing of an agent message.
